// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package queries

import (
	"database/sql"
	"time"
)

type Advertisement struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	ProviderID  int64          `json:"provider_id"`
	Attachment  string         `json:"attachment"`
	Experience  int32          `json:"experience"`
	CategoryID  int64          `json:"category_id"`
	Time        int32          `json:"time"`
	Price       int32          `json:"price"`
	Format      string         `json:"format"`
	Language    string         `json:"language"`
	Description string         `json:"description"`
	MobilePhone sql.NullString `json:"mobile_phone"`
	Email       sql.NullString `json:"email"`
	Telegram    sql.NullString `json:"telegram"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Avatar struct {
	ID         int64  `json:"id"`
	Filename   string `json:"filename"`
	Fileadress string `json:"fileadress"`
	Data       []byte `json:"data"`
	ProviderID int64  `json:"provider_id"`
}

type Category struct {
	ID       int64         `json:"id"`
	Name     string        `json:"name"`
	ParentID sql.NullInt64 `json:"parent_id"`
}

type User struct {
	ID        int64          `json:"id"`
	Name      sql.NullString `json:"name"`
	Email     string         `json:"email"`
	Photo     sql.NullString `json:"photo"`
	Verified  bool           `json:"verified"`
	Password  sql.NullString `json:"password"`
	Role      string         `json:"role"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}
