CREATE TABLE "users" (
    "id" BIGSERIAL PRIMARY KEY,
    "name" VARCHAR,
    "email" VARCHAR NOT NULL UNIQUE,
    "photo" VARCHAR,
    "verified" BOOLEAN NOT NULL DEFAULT FALSE,
    "password" VARCHAR,
    "role" VARCHAR NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);